apiVersion: apps/v1
kind: Deployment
metadata:
  name: URLShortening-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: URLShortening
  template:
    metadata:
      labels:
        app: URLShortening
    spec:
      containers:
      - name: URLShortening
        image: URLShortening:latest
        ports:
        - containerPort: 8080
        env:
        - name: JAVA_OPTS
          value: "-Dspring.profiles.active=prod"
---
apiVersion: v1
kind: Service
metadata:
  name: URLShortening-service
spec:
  selector:
    app: URLShortening
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: URLShortening-external-service
spec:
  selector:
    app: URLShortening
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: LoadBalancer
